---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-deployment
  labels:
    app: sample-app
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
      service: web
      version: v2
  template:
    metadata:
      labels:
        app: sample-app
        service: web
        version: v2
    spec:
      containers:
      - name: web
        image: gitlab.akb-it.ru:4567/emukhanov/emukhanovk8s:stateful
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        env:
          - name: APP_ENV
            value: default_env
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-postgresql
                key: postgres-password
          - name: DATABASE_URL
            value: postgresql://postgres:$(POSTGRES_PASSWORD)@db-postgresql:5432/sample_app_db?pool=5
      imagePullSecrets:
        - name: regcred
      initContainers:
      - name: init-db
        imagePullPolicy: Always
        image: gitlab.akb-it.ru:4567/emukhanov/emukhanovk8s:stateful
        ports:
          - containerPort: 8080
        env:
          - name: APP_ENV
            value: default_env
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-postgresql
                key: postgres-password
          - name: DATABASE_URL
            value: postgresql://postgres:$(POSTGRES_PASSWORD)@db-postgresql:5432/sample_app_db?pool=5
        command: ["bundle","exec","rake","db:prepare"]
        
