---
apiVersion: v1
kind: Service
metadata:
  name: sample-app-{{ .Release.Name }}-service
  labels:
    app: sample-app-{{ .Release.Name }}
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: sample-app-{{ .Release.Name }}